accelerate launch train.py \
    --seed=123 \
    --experience_name="FontDiffuser_training_phase_2_MRS" \
    --data_root="data_examples" \
    --output_dir="outputs/FontDiffuser_2_MRS" \
    --report_to="wandb" \
    --phase_2 \
    --phase_1_ckpt_dir="/scratch/yl10337/important_result/global_step_200000_MR" \
    --scr_ckpt_path="/scratch/yl10337/important_result/global_step_200000_MR/scr_210000.pth" \
    --sc_coefficient=0.01 \
    --num_neg=16 \
    --resolution=96 \
    --style_image_size=96 \
    --content_image_size=96 \
    --content_encoder_downsample_size=3 \
    --channel_attn=True \
    --content_start_channel=64 \
    --style_start_channel=64 \
    --train_batch_size=16 \
    --perceptual_coefficient=0.01 \
    --offset_coefficient=0.5 \
    --max_train_steps=30000 \
    --ckpt_interval=2500 \
    --gradient_accumulation_steps=1 \
    --log_interval=50 \
    --learning_rate=1e-5 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=1000 \
    --drop_prob=0.1 \
    --mixed_precision="no" \
    --validation_content_dir="data_examples/val/c" \
    --validation_style_dir="data_examples/val/s" \
    --validation_gt_dir="data_examples/val/GT" \
    --validation_tmp_dir="data_examples/val/tmp"
    